# Generated by Django 6.0.4 on 2026-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productsize_unique_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('button_text', models.CharField(default='ПОДРОБНЕЕ', max_length=50, verbose_name='Текст кнопки')),
                ('link', models.CharField(default='/', max_length=255, verbose_name='Ссылка (URL или slug)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньшее число = раньше', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
    ]
