# Generated by Django 6.0.4 on 2026-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Начало действия'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Окончание действия'),
        ),
    ]
